version: '3'

services:
  order-service:
    build:
      context: ./services/order_service
    ports:
      - "8000:8000"
    depends_on:
      - dapr
    environment:
      - DAPR_HTTP_PORT=3500
      - DAPR_GRPC_PORT=50001

  dapr:
    image: "daprio/dapr:latest"
    command: ["./placement", "--app-id", "ecommerceapp"]
    ports:
      - "3500:3500"
      - "50001:50001"

  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro