version: '3'

services:
  order-service:
    build:
      context: ./services/order_service
    ports:
      - "8001:80"  # Adjust the port to match the order service's port
    environment:
      - FASTAPI_ENV=development
  dapr:
    image: "daprio/dapr:latest"
    command: ["./placement", "--app-id", "ecommerceapp"]
    ports:
      - "3500:3500"
      - "50001:50001"

  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro